NextSolRemote/Controllers/DepartmentController.cs
using NextSolRemote.Database;
using NextSolRemote.Repository.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NextSolRemote.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentRepo DeptRepo = new DepartmentRepo();
        // GET: Department
        public ActionResult Index()
        {
            var list = DeptRepo.GetAll();
            return View(list);
        }

        public bool AddUpdate(Department model)
        {
            if (model.id == 0)
            {
                DeptRepo.Add(model);
            }
            else
            {
                DeptRepo.Update(model);
            }
            return true;
        }

        public bool Delete(int Id)
        {
            DeptRepo.Delete(Id);
            return true;
        }
    }
}

NextSolRemote/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NextSolRemote.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NextSolRemote/Controllers/UserController.cs
using NextSolRemote.Database;
using NextSolRemote.Repository.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NextSolRemote.Controllers
{
    public class UserController : Controller
    {
        UserRepo UserRepo = new UserRepo();
        DepartmentRepo DeptRepo = new DepartmentRepo();

        public ActionResult Index()
        {
            var list = UserRepo.GetAll();
            ViewBag.Department = DeptRepo.GetAll().Where(f => f.Active == true).ToList();
            return View(list);
        }

        public bool AddUpdate(User model)
        {
            if (model.id == 0)
            {
                UserRepo.Add(model);
            }
            else
            {
                UserRepo.Update(model);
            }
            return true;
        }

        public bool Delete(int Id)
        {
            UserRepo.Delete(Id);
            return true;
        }
    }
}

NextSolRemote/Views/Department/Index.cshtml
@model List<NextSolRemote.Database.Department>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <br />
    <br />
    <div class="row" style="float:right">
        <input type="button" class="btn btn-success" onclick="addDepartment()" value="+ Add New" data-toggle="modal" data-target="#myModal" />
    </div>
    <br />
    <br />
    <div class="row">
        <table class="table table-bordered table-responsive table-striped">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Address
                    </th>
                    <th>
                        Active
                    </th>
                    <th>
                        No of Users
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @item.Address
                        </td>
                        <td>
                            @item.Active
                        </td>
                        <td>
                            @item.Users.Count()
                        </td>
                        <td>
                            @*Some Issue in VS So pass active like that*@
                            <input type="button" class="btn btn-primary" value="Edit" data-toggle="modal" data-target="#myModal" onclick="editDepartment(@item.id, '@item.Name', '@item.Description', '@item.Address', '@(item.Active == true ? "on":"off")')" />
                            <input type="button" class="btn btn-danger" value="Del" data-toggle="modal" data-target="#confirmDepartmentDelete" onclick="deleteDepartment(@item.id)" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>,
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title modelTitle">Add Department</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <input type="number" class="hidden" id="deptId" />
                    <div class="col-md-6">
                        <label>Name<span style="color:red">*</span></label>
                        <input type="text" id="deptName" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Description</label>
                        <input type="text" id="deptDesc" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Address</label>
                        <textarea id="deptAddress" class="form-control"></textarea>
                    </div>
                    <div class="col-md-2">
                        <label>Active</label>
                        <input type="checkbox" id="deptActive" style="width:20px;" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary SaveDepartment" onclick="addUpdate()">Save</button>
            </div>
        </div>
    </div>
</div>

<div id="confirmDepartmentDelete" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete Department</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="danger" style="font-weight:bold; text-align:center">
                        Are You Sure!
                        <br />
                        You want to delete this item!
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
                <button type="button" class="btn btn-primary" onclick="confirmDelete()">YES</button>
            </div>
        </div>
    </div>
</div>

@section scripts {

<script>
    var departmentDeletedId = 0;
    var departmentId = 0;

    function addDepartment() {
        $(".modelTitle").text("Add Department");
        $(".SaveDepartment").text("Save");
        $("#deptId").val(0);
        $("#deptName").val("");
        $("#deptDesc").val("");
        $("#deptAddress").val("");
        $("#deptActive").prop("checked", false);
    }

    function editDepartment(id, name, description, address, active) {
        if (active == "on") {
            $("#deptActive").prop("checked", true);
        }
        else {
            $("#deptActive").prop("checked", false);
        }
        $("#deptName").val(name);
        $("#deptDesc").val(description);
        $("#deptAddress").val(address);
        $("#deptId").val(id);
        $(".modelTitle").text("Update Department");
        $(".SaveDepartment").text("Update");
    }

    function addUpdate() {
        if ($("#deptId").val() == "") {
            departmentId = 0;
        }
        else {
            departmentId = $("#deptId").val()
        }
        var model = {
            Name: $("#deptName").val(),
            Address: $("#deptAddress").val(),
            Description: $("#deptDesc").val(),
            Active: $("#deptActive").prop("checked"),
            id: departmentId
        };
        if (model.Name == "") {
            alert("Please enter required fields!");
            return;
        }

        $.ajax({
            url: "/Department/AddUpdate",
            data: model,
            type: "POST",
            success: function (response) {
                if (response) {
                    alert("Saved Successfully!");
                    location.reload();
                } else {
                    alert("Error!");
                }
            }
        });
    }

    function deleteDepartment(Id) {
        departmentDeletedId = Id;
    }

    function confirmDelete() {
        $.ajax({
            url: "/Department/Delete",
            data: { "Id": departmentDeletedId },
            type: "POST",
            success: function (res) {
                if (res) {
                    alert("Department Deleted Successfully!");
                    location.reload();
                    $("#confirmDepartmentDelete").modal("toggle");
                } else {
                    $("#confirmDepartmentDelete").modal("toggle");
                    alert("There is some error please refresh the page.");
                }
            }
        });
    }
</script>

}

NextSolRemote/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NextSolRemote/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NextSolRemote/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NextSolRemote/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRUD", "Index", "Department", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Department", "Index", "Department")</li>
                    <li>@Html.ActionLink("User", "Index", "User")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

NextSolRemote/Views/User/Index.cshtml
@model List<NextSolRemote.Database.User>

@{
    ViewBag.Title = "Index";
}

<div class="container">
    <br />
    <br />
    <div class="row" style="float:right">
        <input type="button" class="btn btn-success" onclick="addUser()" value="+ Add New" data-toggle="modal" data-target="#myModal" />
    </div>
    <br />
    <br />
    <div class="row">
        <table class="table table-bordered table-responsive table-striped">
            <thead>
                <tr>
                    <th>
                        First Name
                    </th>
                    <th>
                        Last Name
                    </th>
                    <th>
                        Country
                    </th>
                    <th>
                        Address
                    </th>
                    <th>
                        Description
                    </th>
                    <th>
                        Department
                    </th>
                    <th>
                        Active
                    </th>
                    <th>

                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.FirstName
                        </td>
                        <td>
                            @item.LastName
                        </td>
                        <td>
                            @item.Country
                        </td>
                        <td>
                            @item.Address
                        </td>
                        <td>
                            @item.Description
                        </td>
                        <td>
                            @(item.Department?.Name)
                        </td>
                        <td>
                            @item.Active
                        </td>
                        <td>
                            @*Some Issue in VS So pass active like that*@
                            <input type="button" class="btn btn-primary" value="Edit" data-toggle="modal" data-target="#myModal" onclick="editUser(@item.id, '@item.FirstName', '@item.LastName', '@item.Country', '@item.Address', '@item.Description', '@item.DepartmentID', '@(item.Active == true ? "on" : "off")')" />
                            <input type="button" class="btn btn-danger" value="Del" data-toggle="modal" data-target="#confirmDepartmentDelete" onclick="deleteUser(@item.id)" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title modelTitle">Add User</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <input type="number" class="hidden" id="userId" />
                    <div class="col-md-6">
                        <label>First Name<span style="color:red">*</span></label>
                        <input type="text" id="userFirstName" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Last Name<span style="color:red">*</span></label>
                        <input type="text" id="userLastName" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Description</label>
                        <input type="text" id="userDescription" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Department</label>
                        <select class="form-control" id="userDepartment">
                            <option value="">Select Department</option>
                            @foreach (var item in ViewBag.Department)
                            {
                                <option value="@item.id">@item.Name</option>
                            }
                        </select>
                    </div>
                    <div class="col-md-6">
                        <label>Country</label>
                        <input type="text" id="userCountry" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Active</label>
                        <input type="checkbox" id="userActive" style="width:20px;" class="form-control" />
                    </div>
                    <div class="col-md-6">
                        <label>Address</label>
                        <textarea id="userAddress" class="form-control"></textarea>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary saveUser" onclick="addUpdate()">Save</button>
            </div>
        </div>
    </div>
</div>

<div id="confirmUserDelete" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Delete User</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="danger" style="font-weight:bold; text-align:center">
                        Are You Sure!
                        <br />
                        You want to delete this item!
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">NO</button>
                <button type="button" class="btn btn-primary" onclick="confirmUserDelete()">YES</button>
            </div>
        </div>

    </div>
</div>


@section scripts {

    <script>
        var userDeletedId = 0;
        var userId = 0;

        function addUser() {
            $("#modelTitle").text("Add User");
            $(".SaveUser").text("Save");
            $("#userId").val(0);
            $("#userFirstName").val("");
            $("#userLastName").val("");
            $("#userCountry").val("");
            $("#userDescription").val("");
            $("#userAddress").val("");
            $("#userDepartment").val("");
            $("#userActive").prop("checked", false);
        }

        function editUser(id, fName, lName, country, address, description, deptId, active) {
            if (active == "on") {
                $("#userActive").prop("checked", true);
            }
            else {
                $("#userActive").prop("checked", false);
            }
            $("#userId").val(id);
            $("#userFirstName").val(fName);
            $("#userLastName").val(lName);
            $("#userCountry").val(country);
            $("#userDescription").val(description);
            $("#userAddress").val(address);
            $("#userDepartment").val(deptId);
            $(".modelTitle").text("Update User");
            $(".saveUser").text("Update");
        }

        function addUpdate() {
            if ($("#userId").val() == "") {
                userId = 0;
            }
            else {
                userId = parseInt($("#userId").val());
            }
            var model = {
                FirstName: $("#userFirstName").val(),
                LastName: $("#userLastName").val(),
                Country: $("#userCountry").val(),
                Address: $("#userAddress").val(),
                Description: $("#userDescription").val(),
                DepartmentID: $("#userDepartment").val(),
                Active: $("#userActive").prop("checked"),
                id: userId
            };

            if (model.FirstName == "" || model.LastName == "") {
                alert("Please enter required fields!");
                return;
            }

            $.ajax({
                url: "/User/AddUpdate",
                data: model,
                type: "POST",
                success: function (response) {
                    if (response) {
                        alert("Saved Successfully!");
                        location.reload();
                    } else {
                        alert("Error!");
                    }
                }
            });
        }

        function deleteUser(Id) {
            userDeletedId = Id;
            $("#confirmUserDelete").modal();
        }
        function confirmUserDelete() {
            $.ajax({
                url: "/User/Delete",
                data: { "Id": userDeletedId },
                type: "POST",
                success: function (res) {
                    if (res) {
                        alert("User Deleted Successfully!");
                        location.reload();
                        $("#confirmUserDelete").modal('hide');
                    } else {
                        alert("There is some error please refresh the page.");
                    }
                }
            });
        }
    </script>
}